- name: error handling
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id roboshop
    register: user_ouput
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ user_ouput }}"

  - name: create user               #if (exit status)rc!=0, then creating user
    ansible.builtin.command: useradd roboshop
    when: user_ouput.rc != 0

#using  this command "ansible.builtin.command:" cannot be idempotent for user creation. check 21 script.  