- name: play level variables
  hosts: local
  connection: local
  become: yes
  vars_files:
  - course.yaml
  tasks:
  - name: print variables
    vars:
      DURATION: "200HRS"
    ansible.builtin.debug:
      msg: "course is: {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"
