- name: variables passing while running command
  hosts: local
  connection: local
  tasks:
  - name: vars args
    ansible.builtin.debug:
      msg: "Hi, My name is {{NAME}}, Good Morning!! "

#run command as " ansible-playbook -i inventory.ini -e NAME=Sunny 9.var-args.yml"